### PR TITLE
Suspend f.lux

### PR DESCRIPTION
**Pull request by is-this-c**

### CODE REVIEW

**Comment by rafalh** [comment]
I don't really like the idea of finding another process and suspending it without even an option to configure this behavior. Flux itself should be aware of games and behave properly. It shouldn't be responsibility of games to suspend it.
Also messing with other processes can be suspicious from AV software PoV and it actually shouldn't work if process is not running with admin rights...
From what I found Flux can suspend itself if full-screen app is running. Why it's not enough?

**Comment by is-this-c** [comment]
The reality is f.lux is broken.   f.lux interferes with desktop gamma, which completely breaks functionality for **window mode** and **borderless fullscreen**, which makes these modes unusable.

To suspend f.lux administrator rights aren't needed.

**Comment by rafalh** [comment]
Why don't you fix f.lux instead of it's broken? Other games would benefit from it too.

**Comment by is-this-c** [comment]
f.lux is closed source; and I think most games use shaders for gamma these days.

**Comment by rafalh** [comment]
Well, actually using shader for gamma would be cool for Dash Faction. I use some flux alternative for Linux - RedShift and it also has problems with DF because of gamma setting.

**Comment by is-this-c** [comment]
Unfortunately, using a pixel shader for gamma moderately decreases performance.   It's not worth it.

**Comment by is-this-c** [comment]
I did a rewrite and now use `DebugActiveProcess` which works flawlessly and elegantly in comparison to `NtSuspendProcess`.

**Comment by rafalh** [comment]
I do not want to mess with other processes in DF. `DebugActiveProcess` is unacceptable for me. DF is not a debugger.
The only reasonable solution would be to rewrite gamma feature into a shader. Now that DX11 code is merged it should be easier. DX8-9 could use the old way of doing gamma, and DX11 could do it in a shader. Closing it for now, but feel free to reopen or create a new PR if you want to work on it.

**Pull request closed without merging**
