### PR TITLE
Increase fps cap

### PR DESCRIPTION
**Pull request by MartianMadman**
Just my personal solution to (issue #153) you can close this PR if you want, no hard feelings.

### CODE REVIEW

**Comment by MartianMadman** [comment]
Sorry lol I'm new to github I don't know what the hell I'm doing.

**Comment by rafalh** [comment]
Why not remove the limit completely? I don't see any reason to limit it to `99999`.

**Comment by is-this-c** [comment]
> Why not remove the limit completely? I don't see any reason to limit it to `9999`.

maxfps won't be accurate at a high fps, because Sleep's resolution is milliseconds.

**Comment by rafalh** [comment]
> > Why not remove the limit completely? I don't see any reason to limit it to `9999`.
> 
> maxfps won't be accurate at a high fps, because Sleep's resolution is milliseconds.

`Sleep` is not used by Dash for FPS limiting when amount of time to wait is smaller than some amount of ms (check the source code for exact number). Also `Sleep` effective resolution is not always 1 millisecond (its parameter type resolution maybe but it's not all what determines real resolution). It's limited by Windows timer interrupt configuration which used to be about 10 ms IIRC (can be changed using API). But also it would be very silly to expect `Sleep` to being accurate with such intervals considering system does context switch to a different process.
Also if we don't want to cross 1 ms limit than max fps should be 999, not 9999. But I don't see a reason to deny people set any number then (well, except negative ones...)

**Comment by is-this-c** [comment]
The timer interrupt interval is often set to 1 millisecond by games and web browsers AFAIK. However, Sleep apparently works differently after Windows, version 2004.

**Comment by MartianMadman** [comment]
Idk how to remove the limit entirely.

**Comment by rafalh** [comment]
I'll close it for now and remove the limit when flamethrower dependency on FPS is fixed.

**Pull request closed without merging**
