### PR TITLE
Add authorship information to changelog

### PR DESCRIPTION
**Pull request by is-this-c**
I organized my code contributions under my name.

### CODE REVIEW

**Comment by rafalh** [comment]
I'm not sure if I like grouping it into one section, because I didn't see it it many projects but you reminded me that VSCode does it so I guess we could try... But to merge this I would like you to group PRs from other contributors in the unreleased version too so you alone are not treated differently.

**Comment by is-this-c** [comment]
I simplified it and organized every contribution and added missing entry, `Add browser detection for RfServerBrowser 5.1.4`. I think it looks good.

**Comment by GooberRF** [comment]
My 2c: to me, it looks a bit odd to have all contributions listed by contributor _except_ those from @rafalh .

If I were reading the changelog as revised by this PR, without any context/knowledge about Dash or its history, I'd interpret the contributions listed without a specific author credit as being from a group of contributors rather than any one specific person. In that hypothetical, unless I looked at the copyright notice or licensing-info.txt (which I probably wouldn't), I'd not even know rafalh had anything to do with the project.

I'm not familiar with how other projects do it - is it standard practice to list contributions from the repo owner without giving explicit credit to them, then explicitly credit other contributors?

If the way it's currently done is standard, I'd agree with it and have no objection to this being merged as is... personally though, I think it would look cleaner - and be more easily understood by everyone - if rafalh's contributions were also listed in a group labeled with his name under the heading for each release.

**Comment by is-this-c** [comment]
The project owner was placed above external contributors for fairness and indent deleted for simplicity.

**Comment by GooberRF** [comment]
I think it looks great now.

**Pull request merged**
